### ISSUE TITLE
Is there a way to override the complete.blade.php

### ISSUE THREAD

**Issue by hdouanla** [mmanos/laravel-social#8]
I've added the social auth to my app and it works just like a charm.
Thank you.

In the twitter login process the user has to enter an email address and the page from the complete.blade.php template.

My question is: Is there a way to override complete.blade.php inside my application?

Thx in advance

**Comment by fraank** [comment]
You can override every view from packages by creating a new view in packages-folder inside "views"-Folder. In this case your view should be saved here:
"app/views/packages/mmanos/laravel-social/social/complete.blade.php"

Your content should look like this: https://github.com/mmanos/laravel-social/blob/master/src/views/social/complete.blade.php

**Comment by hdouanla** [comment]
Thank you Fraank,
It just worked as expected for me.

**Comment by fraank** [comment]
Perfect, this issue can be closed.
